### ISSUE TITLE
does not support `pathPrefix`

### ISSUE THREAD

**Issue by chadoh** [hashbite/gatsby-transformer-video#22]
When deploying sites at non-root domains, Gatsby allows adding a [pathPrefix](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/path-prefix/).

gatsby-transformer-video currently ignores this setting, resulting in broken videos.

**Comment by mainframeai** [comment]
Is ther esomething new on this issue ? I woudl love to use this. But this is at the moment kind of a dealbreaker. :-(… Otherweise it is exactly what i need.

**Comment by chadoh** [comment]
Workaround: import `withPrefix` from `gatsby` and use it in a `Video` component:

```ts
import React from 'react'
import { withPrefix } from 'gatsby'
import useVideoData from "../../hooks/useVideoData"

export type VideoProps = React.DetailedHTMLProps<
  React.VideoHTMLAttributes<HTMLVideoElement>,
  HTMLVideoElement
> & {
  src: string
}

const Video: React.FC<VideoProps> = ({ src, ...props }) => {
  const { videoH264 } = useVideoData(src)
  return (
    <video playsInline muted preload="auto" {...props}>
      <source src={withPrefix(videoH264.path!)} />
    </video>
  )
}

export default Video
```

Example taken from [TENK-DAO/frontend-starter](https://github.com/TENK-DAO/frontend-starter/blob/f06ceb594b330651be8392c30d315ffa67c3a78d/src/components/video/index.tsx)
